module.exports = {
  TRANSPORT_MODES: {
    BUS: 'BUS',
    TRAIN: 'TRAIN',
    TAXI: 'TAXI',
    THREE_WHEELER: 'THREE_WHEELER',
    WALK: 'WALK'
  },
  PREFERENCE_TYPES: {
    FASTEST: 'FASTEST',
    CHEAPEST: 'CHEAPEST',
    MIN_WALKING: 'MIN_WALKING',
    MIN_TRANSFERS: 'MIN_TRANSFERS',
    MOST_RELIABLE: 'MOST_RELIABLE'
  },
  DISRUPTION_TYPES: {
    DELAY: 'DELAY',
    CANCELLATION: 'CANCELLATION',
    ROAD_CLOSURE: 'ROAD_CLOSURE',
    TRAFFIC: 'TRAFFIC',
    ROUTE_INTERRUPTION: 'ROUTE_INTERRUPTION'
  },
  RISK_LEVELS: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH'
  }
};
