module.exports = {
  DISRUPTION_TYPES: {
    DELAY: "DELAY",
    CANCELLATION: "CANCELLATION",
    ROAD_CLOSURE: "ROAD_CLOSURE",
    TRAFFIC: "TRAFFIC",
    ROUTE_INTERRUPTION: "ROUTE_INTERRUPTION",
  },

  DISRUPTION_SEVERITY: {
    LOW: "LOW",
    MEDIUM: "MEDIUM",
    HIGH: "HIGH",
    CRITICAL: "CRITICAL",
  },

  DISRUPTION_STATUS: {
    ACTIVE: "ACTIVE",
    RESOLVED: "RESOLVED",
    SCHEDULED: "SCHEDULED",
  },

  NOTIFICATION_TYPES: {
    DELAY: "DELAY",
    CONNECTION_RISK: "CONNECTION_RISK",
    JOURNEY_CHANGE: "JOURNEY_CHANGE",
    ALTERNATIVE_ROUTE: "ALTERNATIVE_ROUTE",
    TRANSFER_REMINDER: "TRANSFER_REMINDER",
    DISRUPTION: "DISRUPTION",
  },

  NOTIFICATION_PRIORITY: {
    LOW: "LOW",
    NORMAL: "NORMAL",
    HIGH: "HIGH",
    CRITICAL: "CRITICAL",
  },

  USER_ROLES: {
    PASSENGER: "passenger",
    ADMIN: "admin",
  },
};
